### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [m1Myp/tsilinykh_19214#1]
Ваш репозиторий потерял, поэтому с опозданием ишуя
1) 0 0 0 
2) С учетом пункта 1, переделайте обработку граничных условий на паттерн матчинг

**Comment by m1Myp** [comment]
fixed

**Comment by ankutalev** [comment]
Принимаю.
Вот как раз, чтобы не создавать файлы с названием 1.1 ,1.2 и существуют системы контроля версий, которой я пытаюсь Вас научиться пользоваться. Почитайте как-нибудь в свободное время про git подробней =)
