### ISSUE TITLE
lab 0 

### ISSUE THREAD

**Issue by ankutalev** [m1Myp/tsilinykh_19214#2]
https://github.com/m1Myp/tsilinykh_19214/blob/7f86918114dba348ca01f07b9acf5feaf024b9e7/lab0.hs#L26

Я совсем забыл отметить, когда принимал лично - foldl/foldr считаются станарнтыми функциями = ) Можете написать свой и/или просто сделать на аккумуляторе

**Comment by m1Myp** [comment]
Fixed

**Comment by ankutalev** [comment]
принято
